### ISSUE TITLE
Inquiry About Training NeuralODE with AODE for Simulation Model

### ISSUE THREAD

**Issue by DengYaosheng** [MohammadKasaei/SoftRobotSimulator#1]
Dear Mohammad Kasaei,

My name is DENG, and I am currently working on a project involving NeuralODEs. I came across this wonderful work, which I found both inspiring and insightful.

I am particularly interested in understanding how the simulation model is trained using AODE in your implementation. Could you kindly provide guidance or share some insights into the training process of NeuralODE in this context? Specifically, I would greatly appreciate any details about the key steps, challenges, or considerations during the training phase.

Thank you very much for your time and support. I genuinely appreciate any advice or resources you could share, and I look forward to learning from your expertise.

Best regards,

**Comment by MohammadKasaei** [comment]
Dear Deng,

Thank you for your kind words and interest in our work! Regarding the training process, I added the trainer to the scripts/trainer_ANODE.py. Instead of using our dataset, we employ a model and sample directly from it. To ensure consistent and repeatable inputs, I set the random seed to values from 0 to 24, generating exactly 25 points for training. This approach helps maintain control over the data sampling process.

I hope this clarifies the methodology. 

Best regards,
Mohammad Kasaei

**Comment by DengYaosheng** [comment]
Dear Mohammad Kasaei,  

Thank you very much for your detailed explanation and for sharing your work! I truly appreciate your generosity in making this research available and your time in helping me understand the methodology.  

I will study this work thoroughly and try to grasp the valuable insights it offers. If opportunities arise in the future, I hope we might have the chance to collaborate and exchange ideas further.  

Thank you again for your guidance and support!  

Best regards,  
Deng
